backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: categories
    label: Categories
    folder: content/categories/
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields: 
      - {name: name, label: Name}
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content/post'
    create: true
    slug: '{{slug}}'
    description: 'Simrik Services website content.'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: categories
        label: Categories
        widget: relation
        collection: "categories"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
        multiple: true
      - {label: “Save as Draft”, name: “draft”, required: false, widget: “boolean”, default: true}
  - name: 'testimonials'
    label: 'Testimonials'
    label_singular: 'Testimonial'
    folder: 'content/testimonial'
    create: true
    slug: '{{slug}}'
    text1: 'What Our Clients Are Saying'
    text2: 'DON’T JUST TAKE OUR WORD FOR IT'
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Rating', name: 'rating', widget: 'number' }
      - name: categories
        label: Categories
        widget: relation
        collection: "categories"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
        multiple: true
      - {label: “Save as Draft”, name: “draft”, required: false, widget: “boolean”, default: true}
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "data/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - label: "Slider Texts"
            name: slidertext
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: "Sub Text", name: subtext, widget: string}
              - {label: More, name: more, widget: markdown} 
          - label: "Main Texts"
            name: maintexts
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: "Sub Text", name: subtext, widget: string}
              - {label: "Link", name: link, widget: string}
          - label: "About Texts"
            name: abouttexts
            widget: 'markdown'
          - {label: 'About PNG Image', name: aboutimage, widget: image}
          - {label: "Footer Slogan", name: subtext, widget: string}
          - {label: "Countries", name: countries, widget: number}
          - {label: "Since", name: since, widget: number}
          - {label: "Construction Projects", name: projectsno, widget: number}
          - {label: "Security Clients", name: clientsno, widget: number}
      - label: "About Page"
        name: "about"
        file: "data/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Contacts"
        name: "locations"
        file: "data/contacts.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string} 
              - {label: Location, name: map, widget: map}