backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blogs'
    label_singular: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    description: 'My Cool Blogs'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - label: "Home Page"
        name: "home"
        file: "site/content/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - label: "Slider Texts"
            name: slidertext
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: "Sub Text", name: subtext, widget: string}
              - {label: More, name: more, widget: string} 
          - label: "Main Texts"
            name: maintexts
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: "Sub Text", name: subtext, widget: string}
          - label: "About Texts"
            name: abouttexts
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: "Sub Text", name: subtext, widget: string}
              - {label: "Icon", name: iconname, widget: string}
          - {label: 'About PNG Image', name: aboutimage, widget: image}
          - {label: "Footer Slogan", name: subtext, widget: string}
      - label: "About Page"
        name: "about"
        file: "site/content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string} 