backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: homepagesliders
    label: Home Page Sliders
    label_singular: Home Page Slider
    folder: content/homepagesliders/
    create: true
    slug: "{{slug}}"
    summary: '{{order}}. {{title}}'
    sortable_fields: ['order', 'title']
    fields: 
      - {label: Title, name: title, widget: string}
      - {label: "Sub Text", name: subtext, widget: string}
      - {label: Body, name: body, widget: markdown}
      - { label: 'Display Order', name: 'order', widget: number } 
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
  - name: about
    label: About
    folder: content/about/
    create: true
    slug: "{{slug}}"
    summary: '{{order}}. {{title}}'
    sortable_fields: ['order', 'title']
    fields: 
      - {label: Title, name: title, widget: string}
      - {label: "Sub Text", name: subtext, widget: markdown}
      - {label: Body, name: body, widget: markdown}
      - {label: 'Heading Image', name: headingimage, widget: image} 
      - {label: 'Main Image', name: mainimage, widget: image, required: false}
      - { label: 'Display Order', name: 'order', widget: number } 
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: "Type", name: "type", widget: "hidden", default: "about" }
  - name: 'services'
    label: 'Services'
    label_singular: 'Service'
    folder: 'content/services'
    create: true
    slug: '{{slug}}'
    summary: '{{order}}. {{title}}'
    sortable_fields: ['order', 'title']
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Icon Name', name: 'iconname', widget: 'string' }
      - { label: 'Heading Image', name: headingimage, widget: image, required: false } 
      - { label: 'Main Image', name: mainimage, widget: image, required: false }
      - { label: 'Display Order', name: 'order', widget: number } 
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: "Type", name: "type", widget: "hidden", default: "services" }
  - name: 'teamnepal'
    label: 'Team Nepal'
    folder: 'content/nepal-team'
    create: true
    slug: '{{slug}}'
    summary: '{{order}}. {{title}}'
    sortable_fields: ['order', 'title']
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Position', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Photo', name: photo, widget: image, required: false  } 
      - { label: 'Facebook', name: facebook, widget: string, required: false } 
      - { label: 'Twitter', name: twitter, widget: string, required: false } 
      - { label: 'Instagram', name: instagram, widget: string, required: false }
      - { label: 'Display Order', name: 'order', widget: number }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: "Type", name: "type", widget: "hidden", default: "team" }
  - name: 'teamhk'
    label: 'Team HK'
    folder: 'content/hk-team'
    create: true
    slug: '{{slug}}'
    summary: '{{order}}. {{title}}'
    sortable_fields: ['order', 'title']
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Position', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Photo', name: photo, widget: image, required: false  } 
      - { label: 'Facebook', name: facebook, widget: string, required: false } 
      - { label: 'Twitter', name: twitter, widget: string, required: false } 
      - { label: 'Instagram', name: instagram, widget: string, required: false }
      - { label: 'Display Order', name: 'order', widget: number }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: "Type", name: "type", widget: "hidden", default: "team" }
  - name: 'teamuk'
    label: 'Team UK'
    folder: 'content/uk-team'
    create: true
    slug: '{{slug}}'
    summary: '{{order}}. {{title}}'
    sortable_fields: ['order', 'title']
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Position', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Photo', name: photo, widget: image, required: false  } 
      - { label: 'Facebook', name: facebook, widget: string, required: false } 
      - { label: 'Twitter', name: twitter, widget: string, required: false } 
      - { label: 'Instagram', name: instagram, widget: string, required: false }
      - { label: 'Display Order', name: 'order', widget: number }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: "Type", name: "type", widget: "hidden", default: "team" }
  - name: trainings
    label: Trainings
    folder: content/trainings/
    create: true
    slug: "{{slug}}"
    summary: '{{order}}. {{title}}'
    sortable_fields: ['order', 'title']
    fields: 
      - {label: Title, name: title, widget: string}
      - {label: "Sub Text", name: subtext, widget: markdown}
      - {label: Body, name: body, widget: markdown}
      - {label: Video ID, name: vidid, widget: string}
      - {label: Duration, name: duration, widget: string}
      - {label: 'Heading Image', name: headingimage, widget: image, required: false} 
      - {label: 'Main Image', name: mainimage, widget: image, required: false} 
      - { label: 'Display Order', name: 'order', widget: number }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: "Type", name: "type", widget: "hidden", default: "trainings" }
  - name: 'testimonials'
    label: 'Testimonials'
    label_singular: 'Testimonial'
    folder: 'content/testimonial'
    create: true
    slug: '{{slug}}'
    summary: '{{order}}. {{title}}'
    sortable_fields: ['order', 'title']
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Rating', name: 'rating', widget: 'number' }
      - { label: 'Display Order', name: 'order', widget: number }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: "Type", name: "type", widget: "hidden", default: "testimonials" }
  - name: 'newsevents'
    label: 'News & Events'
    label_singular: 'News / Event'
    folder: 'content/newsevents'
    create: true
    slug: '{{slug}}'
    summary: '{{date}} {{title}} - ({{writer}})'
    sortable_fields: ['order', 'title', 'writer']
    fields:
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Keyword', name: 'keyword', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Main Image', name: mainimage, widget: image, allow_multiple: false }
      - label: 'Multiple Images'
        name: 'multipleimages'
        widget: list
        required: false
        fields:
          - {label: Caption, name: title, widget: string}
          - {label: Photo, name: photo, widget: image}
      - { label: 'Writer Name', name: 'writer', widget: 'string', default: 'SSGF' }
      - { label: 'Writer Photo', name: writerphoto, widget: image, allow_multiple: false, required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: "Type", name: "type", widget: "hidden", default: "newsevents" }

  - name: 'settings'
    label: 'Settings'
    editor:
      preview: false
    files:
      - label: "Settings"
        name: "settings"
        file: "data/settings.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Hong Kong Email, name: hkemail, widget: string}
          - {label: Hong Kong Phone, name: hkphone, widget: string}
          - {label: Nepal Email, name: nepalemail, widget: string}
          - {label: Nepal Phone, name: nepalphone, widget: string}
          - {label: UK Email, name: ukemail, widget: string}
          - {label: UK Phone, name: ukphone, widget: string}
          - {label: Service Subtext, name: servicesubtext, widget: markdown}
          - {label: Testimonial subtext, name: testimonialsubtext, widget: markdown }
          - {label: News Subtext, name: newssubtext, widget: markdown}
          - {label: 'Social Image', name: socialimage, widget: image}
          - {label: "Footer Slogan", name: subtext, widget: string}
          - {label: "Countries", name: countries, widget: number}
          - {label: "Since", name: since, widget: number}
          - {label: "Service Scope", name: scopes, widget: number}
          - {label: "No of Clients", name: clientsno, widget: number}
          - {label: Hongkong Contact, name: hkcontact, widget: markdown}
          - {label: Nepal Contact, name: nepalcontact, widget: markdown}
          - {label: UK Contact, name: ukcontact, widget: markdown}
          - {label: Hongkong Location, name: hkmap, widget: map}
          - {label: Nepal Location, name: nepalmap, widget: map}
          - {label: UK Location, name: ukmap, widget: map}